services:
  api:
    image: api-submodule:dev
    container_name: api
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
    restart: unless-stopped

  worker:
    image: hello-api:latest
    container_name: worker
    ports:
      - "8090:8080"
    environment:
      PORT: "8080"
    restart: unless-stopped
